/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SupplyChainInterface extends Interface {
    getFunction(nameOrSignature: "addCrop" | "cropCount" | "crops"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CropAdded"): EventFragment;

    encodeFunctionData(functionFragment: 'addCrop', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cropCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'crops', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCrop', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cropCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'crops', data: BytesLike): Result;
  }

  
    export namespace CropAddedEvent {
      export type InputTuple = [id: BigNumberish, name: string, quantity: BigNumberish, price: BigNumberish, farmer: AddressLike];
      export type OutputTuple = [id: bigint, name: string, quantity: bigint, price: bigint, farmer: string];
      export interface OutputObject {id: bigint, name: string, quantity: bigint, price: bigint, farmer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SupplyChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): SupplyChain;
    waitForDeployment(): Promise<this>;

    interface: SupplyChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCrop: TypedContractMethod<
      [_name: string, _quantity: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cropCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    crops: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint] & {id: bigint, name: string, quantity: bigint, price: bigint, farmer: string, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCrop'): TypedContractMethod<
      [_name: string, _quantity: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cropCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'crops'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint] & {id: bigint, name: string, quantity: bigint, price: bigint, farmer: string, timestamp: bigint }],
      'view'
    >;

    getEvent(key: 'CropAdded'): TypedContractEvent<CropAddedEvent.InputTuple, CropAddedEvent.OutputTuple, CropAddedEvent.OutputObject>;

    filters: {
      
      'CropAdded(uint256,string,uint256,uint256,address)': TypedContractEvent<CropAddedEvent.InputTuple, CropAddedEvent.OutputTuple, CropAddedEvent.OutputObject>;
      CropAdded: TypedContractEvent<CropAddedEvent.InputTuple, CropAddedEvent.OutputTuple, CropAddedEvent.OutputObject>;
    
    };
  }